### ISSUE TITLE
May add localization for mod's workshop Title/Description

### ISSUE THREAD

**Issue by urgiv** [BlockCrusader/ArtificerMod#5]
I think workshop support what Title/Description to display, based on visitor's Steam language.
Mod Creator could use 'Edit title & description', choose Simplified Chinese and put content of Simplified Chinese_workshop.txt (https://github.com/urgiv/zh-Hans-localization-files-for-tml-1.4.4/blob/main/workshop%20Title%20%26%20Description%20here/ArtificerMod/Simplified%20Chinese_workshop.txt) in it.

**Comment by BlockCrusader** [comment]
Alright, I can add this no problem. Do note that I won't be capable of updating the translated description myself whenever I update the English description.

**Comment by BlockCrusader** [comment]
If you ever want to update the translated description, feel free to also add in a line that the description was translated by you.

**Comment by urgiv** [comment]
Just pin me when new Items or Features are added, I'll update the workshop texts.
